import { useShallow } from "zustand/react/shallow";
import { useDataManagementStore } from "../DataManagementStore";
import {
    selectActiveColumns,
    selectActiveSheet,
    selectSheetColumnMap,
    selectSheetNames,
} from "./fileHierarchySlice";
import { selectCanBuildSchema, selectCanSave } from "./dirtyGuardSlice";
import { selectIsNewMode } from "./modelSlice";

export function useDataManagementState() {
    return useDataManagementStore(useShallow(s => ({
        selectedData: s.selectedData,
        searchQuery: s.searchQuery,
        activeTab: s.activeTab,
        analysisName: s.analysisName,
        analysisDesc: s.analysisDesc,
        analysisCategory: s.analysisCategory,
        layoutMode: s.layoutMode,
        leftPanelCollapsed: s.leftPanelCollapsed,
        rightPanelVisible: s.rightPanelVisible,
        errorMsg: s.errorMsg,
        saveStatus: s.saveStatus,
        schemaResult: s.schemaResult,
        saveDatasetsJson: s.saveDatasetsJson,
        suggestedQueries: s.suggestedQueries,
        streamLogs: s.streamLogs,
        isBuilding: s.isBuilding,
        consolePhase: s.consolePhase,
        poolItems: s.poolItems,
        activePoolId: s.activePoolId,
        localFile: s.localFile,
        currentFile: s.currentFile,
        selectedToolId: s.selectedToolId,
        toolPreviewResult: s.toolPreviewResult,
        isPreviewLoading: s.isPreviewLoading,
        execQuery: s.execQuery,
        execQueryPlaceholder: s.execQueryPlaceholder,
        dbForm: s.dbForm,
        isDbLocked: s.isDbLocked,
        dbColumns: s.dbColumns,
        connStatus: s.connStatus,
        isConnecting: s.isConnecting,
        dirtyModalOpen: s.dirtyModalOpen,
        isPoolDirty: s.isPoolDirty,
        hasActiveSchema: s.hasActiveSchema,
        isNameDuplicate: s.isNameDuplicate,
        loadedModelName: s.loadedModelName,
        loadedModelDid: s.loadedModelDid,
    })));
}

export function useDataManagementActions() {
    return useDataManagementStore(useShallow(s => ({
        setSearchQuery: s.setSearchQuery,
        setActiveTab: s.setActiveTab,
        setAnalysisName: s.setAnalysisName,
        setAnalysisDesc: s.setAnalysisDesc,
        setAnalysisCategory: s.setAnalysisCategory,
        enterDetailMode: s.enterDetailMode,
        enterBrowseMode: s.enterBrowseMode,
        toggleLeftPanel: s.toggleLeftPanel,
        setRightPanelVisible: s.setRightPanelVisible,
        toggleRightPanel: s.toggleRightPanel,
        setErrorMsg: s.setErrorMsg,
        setSaveStatus: s.setSaveStatus,
        setSchemaResult: s.setSchemaResult,
        setSaveDatasetsJson: s.setSaveDatasetsJson,
        setSuggestedQueries: s.setSuggestedQueries,
        appendStreamLog: s.appendStreamLog,
        clearStreamLogs: s.clearStreamLogs,
        setIsBuilding: s.setIsBuilding,
        setConsolePhase: s.setConsolePhase,
        resetAll: s.resetAll,
        startNewAnalysis: s.startNewAnalysis,
        hydrateFromModel: s.hydrateFromModel,
        setUploadedFile: s.setUploadedFile,
        clearFile: s.clearFile,
        setActiveSheetByName: s.setActiveSheetByName,
        toggleColumnByIndex: s.toggleColumnByIndex,
        restoreFileFromPool: s.restoreFileFromPool,
        addFileToPool: s.addFileToPool,
        addToolToPool: s.addToolToPool,
        addDbToPool: s.addDbToPool,
        removeFromPool: s.removeFromPool,
        selectPoolItem: s.selectPoolItem,
        clearActivePoolItem: s.clearActivePoolItem,
        setPoolFromModel: s.setPoolFromModel,
        refreshPoolToolDisplayNames: s.refreshPoolToolDisplayNames,
        setSelectedToolId: s.setSelectedToolId,
        setToolPreviewResult: s.setToolPreviewResult,
        setPreviewLoading: s.setPreviewLoading,
        setExecQuery: s.setExecQuery,
        setExecQueryPlaceholder: s.setExecQueryPlaceholder,
        updateDbField: s.updateDbField,
        setDbVendor: s.setDbVendor,
        setDbColumns: s.setDbColumns,
        toggleDbColumn: s.toggleDbColumn,
        setConnStatus: s.setConnStatus,
        setIsConnecting: s.setIsConnecting,
        restoreDbFromPool: s.restoreDbFromPool,
        evaluatePoolDirty: s.evaluatePoolDirty,
        evaluateName: s.evaluateName,
        attemptSave: s.attemptSave,
        attemptBuildSchema: s.attemptBuildSchema,
        setHasActiveSchema: s.setHasActiveSchema,
        closeDirtyModal: s.closeDirtyModal,
        updateFileInPool: s.updateFileInPool,
    })));
}

export function useDataManagementDerived() {
    const state = useDataManagementState();
    return {
        isNewMode: selectIsNewMode(state),
        canSave: selectCanSave(state.analysisName, state),
        canBuildSchema: selectCanBuildSchema(state),
        fileSheets: selectSheetNames(state),
        fileColumns: selectActiveColumns(state),
        activeSheet: selectActiveSheet(state),
        selectedSheet: selectActiveSheet(state)?.name ?? "",
        sheetColumnMap: selectSheetColumnMap(state),
    };
}
