import {createTheme, type CSSVariablesResolver} from "@mantine/core";
import type {SageThemePreset} from "./types";
import {FONT_FAMILY, FONT_MONO, sageBlue, sageSlate, sageTeal, sageZinc} from "./sharedColors";

/**
 * ④ 권장안 — Light Top + Icon Rail + Adaptive Rail/Main (light/dark)
 */
const theme = createTheme({
    fontFamily: FONT_FAMILY,
    fontFamilyMonospace: FONT_MONO,
    primaryColor: "sageTeal",
    primaryShade: 6,
    defaultRadius: "sm",
    colors: {
        sageTeal,
        sageBlue,
        sageSlate,
        sageZinc,
    },
    components: {
        Paper: {
            defaultProps: {
                bg: "var(--sage-surface-card)",
            },
        },
    },
    other: {
        layoutTopbarHeight: 48,
        layoutNavWidth: 240,
        layoutPanelLeftWidth: 280,
        layoutPanelRightWidth: 360,
    },
});

export const cssVariablesResolver: CSSVariablesResolver = () => ({
    variables: {
        "--sage-font-mono": FONT_MONO,
        "--sage-brand-secondary": "#0090da",
        "--sage-status-running": "#22c55e",
        "--sage-status-pending": "#f59e0b",
        "--sage-status-failed": "#ef4444",
        "--sage-status-idle": "#a1a1aa",
        "--sage-category-data": "#0d9488",
        "--sage-category-report": "#2563eb",
        "--sage-category-tool": "#ea580c",
        "--sage-category-dashboard": "#7c3aed",
        "--sage-kpi-delta-up": "#059669",
        "--sage-kpi-delta-down": "#dc2626",
        "--sage-chart-series-1": "#0d9488",
        "--sage-chart-series-2": "#2563eb",
        "--sage-chart-series-3": "#7c3aed",
        "--sage-chart-series-4": "#f59e0b",
        "--sage-card-radius": "12px",
        "--sage-layout-topbar-height": "48px",
        "--sage-layout-nav-width": "240px",
        "--sage-layout-context-header-height": "44px",
        "--sage-layout-panel-left-width": "280px",
        "--sage-layout-panel-right-width": "360px",
        "--sage-button-radius": "6px",
        "--sage-border-active": "#0d9488",
        "--sage-focus-ring": "#0d9488",
    },
    light: {
        /** Light Top Bar */
        "--sage-topbar-bg": "#ffffff",
        "--sage-topbar-bg-hover": "#f4f4f5",
        "--sage-topbar-text": "#18181b",
        "--sage-topbar-text-muted": "#71717a",
        "--sage-topbar-border": "#e4e4e7",
        "--sage-topbar-search-bg": "#f4f4f5",
        "--sage-topbar-search-text": "#a1a1aa",
        "--sage-topbar-chip-bg": "#f4f4f5",
        "--sage-topbar-icon": "#71717a",
        /** Rail + Main */
        "--sage-nav-bg": "#ffffff",
        "--sage-nav-bg-hover": "#f4f4f5",
        "--sage-nav-bg-active": "#f0fdfa",
        "--sage-nav-text": "#71717a",
        "--sage-nav-text-hover": "#18181b",
        "--sage-nav-text-active": "#0d9488",
        "--sage-nav-active-indicator": "#0d9488",
        "--sage-page-bg": "#f4f4f5",
        "--sage-page-bg-dashboard": "#f0f4f8",
        "--sage-surface-panel": "#ffffff",
        "--sage-surface-card": "#ffffff",
        "--sage-surface-code": "#f8fafc",
        "--sage-border-color": "#e4e4e7",
        "--sage-input-border": "#e4e4e7",
        "--sage-brand-primary": "#0d9488",
        "--sage-brand-primary-hover": "#0f766e",
        "--sage-brand-primary-subtle": "#ccfbf1",
        "--sage-btn-secondary-bg": "#ffffff",
        "--sage-kpi-label-color": "#64748b",
        "--sage-recent-muted": "#64748b",
        "--sage-text-primary": "#18181b",
        "--sage-text-secondary": "#3f3f46",
        "--sage-text-muted": "#64748b",
        "--sage-text-hint": "#94a3b8",
        "--sage-surface-muted": "#f4f4f5",
        "--sage-table-header-bg": "rgba(248, 250, 252, 0.7)",
        "--sage-table-row-border": "#f1f5f9",
        "--sage-badge-ok-bg": "#dcfce7",
        "--sage-badge-ok-text": "#16a34a",
        "--sage-badge-muted-bg": "#f1f5f9",
        "--sage-badge-muted-text": "#94a3b8",
        "--sage-tag-bg": "#eff6ff",
        "--sage-tag-text": "#2563eb",
        "--sage-tag-border": "#dbeafe",
        "--sage-metric-accent": "#2563eb",
        "--sage-kpi-hover-shadow": "0 2px 8px 0 rgba(15, 23, 42, 0.1), 0 4px 16px 0 rgba(15, 23, 42, 0.08)",
        "--mantine-color-text": "#3f3f46",
        "--mantine-color-body": "#f4f4f5",
    },
    dark: {
        /** Elevated Top Bar — 다크 모드 (#27272A) */
        "--sage-topbar-bg": "#27272a",
        "--sage-topbar-bg-hover": "#3f3f46",
        "--sage-topbar-text": "#fafafa",
        "--sage-topbar-text-muted": "#a1a1aa",
        "--sage-topbar-border": "#3f3f46",
        "--sage-topbar-search-bg": "#3f3f46",
        "--sage-topbar-search-text": "#a1a1aa",
        "--sage-topbar-chip-bg": "#3f3f46",
        "--sage-topbar-icon": "#a1a1aa",
        /** Rail + Main — Dark */
        "--sage-nav-bg": "#27272a",
        "--sage-nav-bg-hover": "#3f3f46",
        "--sage-nav-bg-active": "#134e4a",
        "--sage-nav-text": "#a1a1aa",
        "--sage-nav-text-hover": "#fafafa",
        "--sage-nav-text-active": "#14b8a6",
        "--sage-nav-active-indicator": "#14b8a6",
        "--sage-page-bg": "#18181b",
        "--sage-page-bg-dashboard": "#18181b",
        "--sage-surface-panel": "#27272a",
        "--sage-surface-card": "#27272a",
        "--sage-surface-code": "#3f3f46",
        "--sage-border-color": "#3f3f46",
        "--sage-input-border": "#52525b",
        "--sage-brand-primary": "#14b8a6",
        "--sage-brand-primary-hover": "#0d9488",
        "--sage-brand-primary-subtle": "#134e4a",
        "--sage-btn-secondary-bg": "#27272a",
        "--sage-kpi-label-color": "#a1a1aa",
        "--sage-recent-muted": "#a1a1aa",
        "--sage-text-primary": "#fafafa",
        "--sage-text-secondary": "#e4e4e7",
        "--sage-text-muted": "#a1a1aa",
        "--sage-text-hint": "#71717a",
        "--sage-surface-muted": "#3f3f46",
        "--sage-table-header-bg": "rgba(63, 63, 70, 0.6)",
        "--sage-table-row-border": "#3f3f46",
        "--sage-badge-ok-bg": "#134e4a",
        "--sage-badge-ok-text": "#5eead4",
        "--sage-badge-muted-bg": "#3f3f46",
        "--sage-badge-muted-text": "#a1a1aa",
        "--sage-tag-bg": "#1e3a5f",
        "--sage-tag-text": "#93c5fd",
        "--sage-tag-border": "#1e40af",
        "--sage-metric-accent": "#60a5fa",
        "--sage-kpi-hover-shadow": "0 2px 8px 0 rgba(0, 0, 0, 0.35), 0 4px 16px 0 rgba(0, 0, 0, 0.25)",
        "--mantine-color-text": "#fafafa",
        "--mantine-color-body": "#18181b",
    },
});

export const recommendedPreset: SageThemePreset = {
    id: "recommended",
    label: "권장안 (Hybrid)",
    description: "Light Top (Light) / #27272A Top (Dark) + Icon Rail · Adaptive Body",
    theme,
    cssVariablesResolver,
    figmaTokensPath: "figma/command-center.tokens.json",
};
