"""LLM clients, factory, and per-report usage tracking."""

from sage.llm.llms import (
    LLMFactory,
    LLMInterface,
    LLM_REQUEST_TIMEOUT_SEC,
    MAX_RETRIES,
    ClaudeLLM,
    CursorLLM,
    GeminiLLM,
    GPT5LLM,
    Message,
    CONTEXT_JSON_MAX_BYTES,
    CONTEXT_JSON_MAX_LIST_ITEMS,
    CONTEXT_JSON_MAX_DICT_KEYS,
    LLM_ATTACH_MAX_BYTES,
    LLM_ATTACH_RELEASE_MAX_BYTES,
    json_payload_byte_size,
    validate_context_json_value,
    validate_llm_attach,
)
from sage.llm.usage import (
    LLMUsageStats,
    begin_report_generation,
    current_usage,
    format_usage_brief,
    log_report_usage_summary,
    persist_report_usage_log,
    record_llm_usage,
    reset_report_generation,
)

__all__ = [
    "LLMFactory",
    "LLMInterface",
    "LLMUsageStats",
    "LLM_REQUEST_TIMEOUT_SEC",
    "MAX_RETRIES",
    "ClaudeLLM",
    "CursorLLM",
    "GeminiLLM",
    "GPT5LLM",
    "Message",
    "CONTEXT_JSON_MAX_BYTES",
    "CONTEXT_JSON_MAX_LIST_ITEMS",
    "CONTEXT_JSON_MAX_DICT_KEYS",
    "LLM_ATTACH_MAX_BYTES",
    "LLM_ATTACH_RELEASE_MAX_BYTES",
    "json_payload_byte_size",
    "validate_context_json_value",
    "validate_llm_attach",
    "begin_report_generation",
    "current_usage",
    "format_usage_brief",
    "log_report_usage_summary",
    "persist_report_usage_log",
    "record_llm_usage",
    "reset_report_generation",
]
