import {createTheme, type CSSVariablesResolver, type MantineColorsTuple} from "@mantine/core";
/*
 * Theme colors are generated by Mantine Colors Generator
 * https://mantine.dev/colors-generator
 */

// SAG-E Dark Blue
const sageDarkBlue: MantineColorsTuple = [
    '#eef4fb',
    '#dbe4f1',
    '#b3c7e5',
    '#88a8da',
    '#658ed1',
    '#4f7ecc',
    '#4375cb',
    '#3564b3',
    '#2c59a1',
    '#0f2545'
];

// SAG-E Blue
const sageBlue: MantineColorsTuple = [
    "#e2faff",
    "#ccefff",
    "#9cddff",
    "#67cafe",
    "#40bafc",
    "#29b0fc",
    "#18abfe",
    "#0090da",
    "#0085cc",
    "#0073b5"
]

/**
 * Premium Slate Palette
 * 1:1 매핑: Tailwind CSS slate 팔레트 기반
 *   [0] slate-50  | [1] slate-100 | [2] slate-200 | [3] slate-300 | [4] slate-400
 *   [5] slate-500 | [6] slate-600 | [7] slate-700 | [8] slate-800 | [9] slate-900
 */
const sageSlate: MantineColorsTuple = [
    '#f8fafc',  // slate-50
    '#f1f5f9',  // slate-100
    '#e2e8f0',  // slate-200
    '#cbd5e1',  // slate-300
    '#94a3b8',  // slate-400
    '#64748b',  // slate-500
    '#475569',  // slate-600
    '#334155',  // slate-700
    '#1e293b',  // slate-800
    '#0f172a',  // slate-900
];

const theme = createTheme({
    fontFamily: "Noto Sans KR, sans-serif",
    /** Fira Code: 코드 에디터 및 JSON 뷰어 전용 모노스페이스 폰트 */
    fontFamilyMonospace: "'Fira Code', 'Cascadia Code', 'Consolas', monospace",
    /** sageBlue를 Primary로 지정 → 인풋 포커스 링이 sageBlue-7 (#0090da)으로 통일 */
    primaryColor: "sageBlue",
    primaryShade: 7,
    colors: {
        sageDarkBlue: sageDarkBlue,
        sageBlue: sageBlue,
        sageSlate: sageSlate,
    },
});

export const cssVariablesResolver: CSSVariablesResolver = () => ({
    variables: {
        /** 코드/JSON 뷰어 공용 폰트 CSS 변수 */
        "--sage-font-mono": "'Fira Code', 'Cascadia Code', 'Consolas', monospace",
        /** 사이드바 기본 배경 (slate-900) */
        "--sage-nav-bg": "#0f172a",
        /** 사이드바 호버 배경 (slate-800) */
        "--sage-nav-bg-hover": "#1e293b",
        /** 사이드바 액티브 배경 (sageBlue-7) */
        "--sage-nav-bg-active": "#0090da",
        /** 프리미엄 테마 경계선 색상 (slate-200) */
        "--sage-border-color": "#e2e8f0",
        /** 본문 페이지 배경 (slate-50) */
        "--sage-page-bg": "#f8fafc",
        /** 사이드바 메뉴 기본 텍스트 (slate-400) */
        "--sage-nav-text": "#94a3b8",
        /** 사이드바 메뉴 호버 텍스트 (slate-100) */
        "--sage-nav-text-hover": "#f1f5f9",
        /** 사이드바 메뉴 활성 텍스트 (white) */
        "--sage-nav-text-active": "#ffffff",
        /** 인풋 기본 테두리 색상 (slate-300) */
        "--sage-input-border": "#cbd5e1",
        /** 인풋 포커스 링 색상 (sageBlue-7) */
        "--sage-focus-ring": "#0090da",
    },
    light: {
        "--mantine-color-text": "#334155",
    },
    dark: {
        "--mantine-color-text": "#f1f5f9",
    }
});

export default theme;
